export type IActiveSiteSplashForm = 'LOGIN' | 'REGISTER'

export type IActiveSiteSplashFormMessage = 
  'ACCOUNT_NEEDED_TO_CREATE_SHEET' |
  'ACCOUNT_NEEDED_TO_UPLOAD_CSV' |
  'CLICK_TO_LOGIN_INSTEAD' |
  'CLICK_TO_REGISTER_INSTEAD' |
  'ERROR_DURING_REGISTRATION'